"""
Parlay History — persistent storage and adaptive probability calibration.

Every parlay generated by ``/parlay`` is saved here.  When the user reports
results with ``/resultado``, each leg is marked W(on) / L(ost) / X(void).
That accumulated data feeds a calibration engine that automatically corrects
future probability estimates, making the parlay builder smarter over time.

Storage
-------
``data/parlay_history.json`` — a JSON array of parlay records.  The file is
written atomically (write-to-tmp then rename) and all access is protected by
``_LOCK`` so concurrent bot jobs cannot corrupt it.

Calibration logic
-----------------
For every (market_type) group with ≥ ``_MIN_SAMPLES`` resolved legs:

  calibration_factor = actual_hit_rate / mean_predicted_prob

  - Factor < 1 → model is *over*-confident → future probs are scaled down
  - Factor > 1 → model is *under*-confident → future probs are scaled up
  - Clamped to [``_CAL_MIN``, ``_CAL_MAX``] to avoid extreme swings

A per-sport factor is also tracked so that, e.g., NBA moneyline predictions
can be corrected independently of soccer totals.

Record structure
----------------
{
  "id":            "P240315-1",
  "created_at":    "2024-03-15T14:30:22Z",
  "tier":          "safe",           // "safe" | "balanced" | "risky"
  "combined_prob": 72.3,
  "legs": [
    {
      "match":          "Burnley vs Bournemouth",
      "pick":           "Over 2.5",
      "market_type":    "totals",
      "sport_emoji":    "⚽",
      "predicted_prob": 82.5,
      "result":         null          // null | "W" | "L" | "X"
    }, …
  ],
  "parlay_result": null               // null | "W" | "L"
}
"""

import json
import logging
import os
import threading
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger(__name__)

# ── Paths ──────────────────────────────────────────────────────────────────────
_BASE_DIR  = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # sports_engine/
_DATA_DIR  = os.path.join(_BASE_DIR, "data")
_HIST_FILE = os.path.join(_DATA_DIR, "parlay_history.json")

# ── Concurrency ────────────────────────────────────────────────────────────────
_LOCK = threading.Lock()

# ── Calibration parameters ─────────────────────────────────────────────────────
# Minimum resolved legs in a group before its calibration factor is trusted.
_MIN_SAMPLES = 5
# Rolling window — only the most recent N resolved legs feed calibration.
# Using a finite window ensures the model adapts to *recent* performance
# rather than being permanently biased by early, potentially unrepresentative data.
_CALIBRATION_WINDOW = 200
# Calibration factor is clamped to this range to avoid extreme corrections.
_CAL_MIN, _CAL_MAX = 0.60, 1.40

# Compiled regex for validating / matching parlay IDs (e.g. "P240315-2").
# Exported so callers (bot.py) can reuse it without duplicating the pattern.
import re as _re
PARLAY_ID_RE = _re.compile(r'^P\d{6}-\d+$', _re.IGNORECASE)


# ── Low-level I/O ──────────────────────────────────────────────────────────────

def _load() -> list:
    """Load the full history list from disk.  Returns [] on any error."""
    if not os.path.exists(_HIST_FILE):
        return []
    try:
        with open(_HIST_FILE, "r", encoding="utf-8") as fh:
            data = json.load(fh)
            return data if isinstance(data, list) else []
    except (json.JSONDecodeError, OSError) as exc:
        logger.warning("parlay_history: could not load %s: %s", _HIST_FILE, exc)
        return []


def _save(records: list) -> None:
    """Atomically write records to disk (tmp → rename)."""
    os.makedirs(_DATA_DIR, exist_ok=True)
    tmp = _HIST_FILE + ".tmp"
    try:
        with open(tmp, "w", encoding="utf-8") as fh:
            json.dump(records, fh, ensure_ascii=False, indent=2)
        os.replace(tmp, _HIST_FILE)
    except OSError as exc:
        logger.error("parlay_history: could not save history: %s", exc)


# ── ID generation ──────────────────────────────────────────────────────────────

def _next_id(records: list) -> str:
    """Return the next sequential parlay ID for today, e.g. ``P240315-3``."""
    today  = datetime.now(timezone.utc).strftime("%y%m%d")
    prefix = f"P{today}-"
    same_day = [r for r in records if r.get("id", "").startswith(prefix)]
    return f"{prefix}{len(same_day) + 1}"


# ── Public API — write ─────────────────────────────────────────────────────────

def save_parlay(legs: list, tier: str, combined_prob: Optional[float]) -> str:
    """
    Persist a generated parlay and return its unique ID.

    Parameters
    ----------
    legs         : list of leg dicts from ``generate_parlay_legs``
    tier         : "safe" | "balanced" | "risky"
    combined_prob: combined probability (%) for this tier's legs

    Returns
    -------
    Unique parlay ID string (e.g. ``"P240315-1"``).
    """
    with _LOCK:
        records = _load()
        pid = _next_id(records)
        record = {
            "id":            pid,
            "created_at":    datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "tier":          tier,
            "combined_prob": combined_prob,
            "parlay_result": None,
            "legs": [
                {
                    "match":          leg.get("match", ""),
                    "pick":           leg.get("pick", ""),
                    "market_type":    leg.get("market_type", ""),
                    "sport_emoji":    leg.get("sport_emoji", ""),
                    "predicted_prob": leg.get("prob"),
                    "result":         None,
                }
                for leg in legs
            ],
        }
        records.append(record)
        _save(records)
        logger.info("parlay_history: saved %s (%d legs, tier=%s)", pid, len(legs), tier)
    return pid


def record_results(parlay_id: str, results: list) -> dict:
    """
    Record win/loss/void results for the legs of a previously saved parlay.

    Parameters
    ----------
    parlay_id : parlay ID string (e.g. ``"P240315-1"``) — case-insensitive.
    results   : list of ``"W"``, ``"L"``, or ``"X"`` (void/cancelled), one
                element per leg.  If shorter than the leg count, remaining
                legs are left as ``None``.

    Returns
    -------
    dict:
      ``found``   – bool
      ``id``      – parlay_id
      ``legs``    – updated legs list (only when found)
      ``overall`` – ``"W"`` / ``"L"`` / ``"X"`` / ``None``
    """
    pid_upper = parlay_id.strip().upper()

    with _LOCK:
        records = _load()
        for rec in records:
            if rec.get("id", "").upper() == pid_upper:
                for i, res in enumerate(results):
                    if i < len(rec["legs"]):
                        rec["legs"][i]["result"] = res.strip().upper()

                # Derive overall parlay result from legs reported so far.
                # "L" is set immediately when any leg is lost.
                # "W" requires ALL legs to have a result (W or X) — no None remaining.
                all_results    = [l["result"] for l in rec["legs"]]
                reported_non_null = [r for r in all_results if r is not None]

                if any(r == "L" for r in reported_non_null):
                    rec["parlay_result"] = "L"
                elif (
                    len(reported_non_null) == len(rec["legs"])
                    and all(r in ("W", "X") for r in reported_non_null)
                ):
                    # Every leg has a result and none are L
                    rec["parlay_result"] = "W"
                else:
                    rec["parlay_result"] = None  # still partially reported

                _save(records)
                logger.info(
                    "parlay_history: recorded results for %s → %s",
                    pid_upper, rec["parlay_result"],
                )
                return {
                    "found":   True,
                    "id":      rec["id"],
                    "legs":    rec["legs"],
                    "overall": rec["parlay_result"],
                }

    return {"found": False, "id": parlay_id}


def get_last_parlay_id() -> Optional[str]:
    """Return the ID of the most recently generated parlay, or None."""
    records = _load()
    return records[-1]["id"] if records else None


# ── Public API — read ──────────────────────────────────────────────────────────

def get_history(limit: int = 20) -> list:
    """Return the ``limit`` most recent parlay records, newest first."""
    records = _load()
    return list(reversed(records[-limit:]))


def get_calibration_stats() -> dict:
    """
    Compute calibration statistics from resolved legs.

    Groups legs by *market_type* (and a combined "overall" group) using the
    most recent ``_CALIBRATION_WINDOW`` resolved legs.

    Returns
    -------
    dict mapping group_key → {
        ``n``          : int   — resolved leg count
        ``predicted``  : float — mean predicted probability (%)
        ``hit_rate``   : float — actual win rate (%)
        ``calibration``: float — hit_rate / predicted  (1.0 = perfect)
        ``bias``       : str   — "OVERCONFIDENT" | "UNDERCONFIDENT" | "OK"
    }
    Also includes ``"overall"`` key with aggregate numbers.
    """
    records = _load()

    # Flatten all resolved legs (W or L only — X voids are excluded)
    resolved: list = []
    for rec in records:
        for leg in rec.get("legs", []):
            if leg.get("result") in ("W", "L") and leg.get("predicted_prob") is not None:
                resolved.append(leg)

    resolved = resolved[-_CALIBRATION_WINDOW:]

    stats: dict = {}
    groups: dict = {}  # market_type → {predicted: [], actual: []}

    for leg in resolved:
        key = leg.get("market_type") or "unknown"
        groups.setdefault(key, {"predicted": [], "actual": []})
        groups[key]["predicted"].append(float(leg["predicted_prob"]))
        groups[key]["actual"].append(1 if leg["result"] == "W" else 0)

    for mtype, data in groups.items():
        n = len(data["predicted"])
        if n == 0:
            continue
        mean_pred = sum(data["predicted"]) / n
        hit_rate  = sum(data["actual"]) / n * 100.0
        cal       = hit_rate / mean_pred if mean_pred > 0 else 1.0
        stats[mtype] = {
            "n":           n,
            "predicted":   round(mean_pred, 1),
            "hit_rate":    round(hit_rate, 1),
            "calibration": round(cal, 3),
            "bias":        _bias_label(cal),
        }

    if resolved:
        all_pred = [l["predicted_prob"] for l in resolved]
        all_act  = [1 if l["result"] == "W" else 0 for l in resolved]
        m_pred   = sum(all_pred) / len(all_pred)
        hit      = sum(all_act)  / len(all_act) * 100.0
        cal      = hit / m_pred if m_pred > 0 else 1.0
        stats["overall"] = {
            "n":           len(resolved),
            "predicted":   round(m_pred, 1),
            "hit_rate":    round(hit, 1),
            "calibration": round(cal, 3),
            "bias":        _bias_label(cal),
        }

    return stats


def calibrate_prob(prob: float, market_type: str) -> float:
    """
    Return a calibration-adjusted probability for a given market type.

    Falls back to the overall calibration factor when the per-market group
    has fewer than ``_MIN_SAMPLES`` resolved legs.  Returns ``prob`` unchanged
    when no calibration data is available yet.

    The correction factor is clamped to ``[_CAL_MIN, _CAL_MAX]`` to prevent
    extreme swings from small samples.
    """
    stats = get_calibration_stats()

    factor = _get_factor(stats.get(market_type))
    if factor is None:
        factor = _get_factor(stats.get("overall"))
    if factor is None:
        return prob  # no data yet — return unchanged

    adjusted = prob * factor
    return round(max(1.0, min(99.0, adjusted)), 1)


# ── Helpers ────────────────────────────────────────────────────────────────────

def _bias_label(cal: float) -> str:
    if cal < 0.85:
        return "OVERCONFIDENT"
    if cal > 1.15:
        return "UNDERCONFIDENT"
    return "OK"


def _get_factor(group_stats: Optional[dict]) -> Optional[float]:
    """Return clamped calibration factor from a stats dict, or None."""
    if not group_stats or group_stats["n"] < _MIN_SAMPLES:
        return None
    raw = group_stats["calibration"]
    return max(_CAL_MIN, min(_CAL_MAX, raw))


# ── Telegram formatters ────────────────────────────────────────────────────────

_NUMBERS = ["1️⃣", "2️⃣", "3️⃣", "4️⃣", "5️⃣"]
_RESULT_EMOJI = {"W": "✅", "L": "❌", "X": "⬜"}
_TIER_EMOJI   = {"safe": "🟢", "balanced": "🟡", "risky": "🔴"}


def format_result_confirmation(record: dict) -> str:
    """Format a result-recording confirmation message for Telegram."""
    pid    = record.get("id", "?")
    legs   = record.get("legs", [])
    ov     = record.get("overall")
    ov_str = {"W": "✅ GANADO", "L": "❌ PERDIDO"}.get(ov, "⏳ Parcialmente registrado")

    lines = [
        f"📋 *Resultados registrados — {pid}*",
        "━━━━━━━━━━━━━━━━━━━━",
    ]
    for i, leg in enumerate(legs):
        num  = _NUMBERS[i] if i < len(_NUMBERS) else f"{i+1}."
        res  = leg.get("result")
        icon = _RESULT_EMOJI.get(res, "⏳") if res else "⏳"
        lines.append(f"  {num} {icon} *{leg['match']}* → _{leg['pick']}_")

    lines += [
        "",
        f"📊 Resultado del parlay: *{ov_str}*",
        "",
        "_Gracias — los datos se usarán para mejorar futuras predicciones._",
    ]
    return "\n".join(lines)


def format_history_summary(records: list, cal_stats: dict) -> str:
    """Format the /historial summary message for Telegram."""
    lines = [
        "╔══════════════════════════════════╗",
        "  📊 HISTORIAL DE PARLAYS",
        "╚══════════════════════════════════╝",
        "",
    ]

    # ── Recent parlays ─────────────────────────────────────────────────────
    if records:
        lines.append("🗓️ *ÚLTIMOS PARLAYS*")
        lines.append("━━━━━━━━━━━━━━━━━━━━")
        for rec in records[:10]:
            pid      = rec.get("id", "?")
            tier     = rec.get("tier", "?")
            tier_e   = _TIER_EMOJI.get(tier, "⚪")
            cp       = rec.get("combined_prob")
            cp_str   = f"`{cp}%`" if cp is not None else "`?`"
            ov       = rec.get("parlay_result")
            ov_icon  = _RESULT_EMOJI.get(ov, "⏳")
            n_legs   = len(rec.get("legs", []))
            date_str = rec.get("created_at", "")[:10]
            lines.append(
                f"  {ov_icon} `{pid}` {tier_e} {tier.upper()} "
                f"({n_legs} patas, {cp_str}) — {date_str}"
            )
        lines.append("")
    else:
        lines.append("_Aún no hay parlays registrados._")
        lines.append("")

    # ── Win rates ─────────────────────────────────────────────────────────
    total_resolved = [r for r in records if r.get("parlay_result") in ("W", "L")]
    if total_resolved:
        wins  = sum(1 for r in total_resolved if r["parlay_result"] == "W")
        total = len(total_resolved)
        lines += [
            "🏆 *RENDIMIENTO*",
            "━━━━━━━━━━━━━━━━━━━━",
            f"  Parlays ganados: *{wins}/{total}* ({round(wins/total*100)}%)",
            "",
        ]

    # ── Calibration stats ──────────────────────────────────────────────────
    ov_cal = cal_stats.get("overall")
    if ov_cal and ov_cal["n"] >= 3:
        bias_emoji = {"OVERCONFIDENT": "📉", "UNDERCONFIDENT": "📈", "OK": "✅"}.get(
            ov_cal["bias"], "❓"
        )
        lines += [
            "🔬 *CALIBRACIÓN DEL MODELO*",
            "━━━━━━━━━━━━━━━━━━━━",
            f"  Patas analizadas: `{ov_cal['n']}`",
            f"  Prob. predicha promedio: `{ov_cal['predicted']}%`",
            f"  Tasa de acierto real: `{ov_cal['hit_rate']}%`",
            f"  Factor de calibración: `{ov_cal['calibration']}`  {bias_emoji} {ov_cal['bias']}",
            "",
        ]
        for mtype, ms in cal_stats.items():
            if mtype == "overall" or ms["n"] < 3:
                continue
            be = {"OVERCONFIDENT": "📉", "UNDERCONFIDENT": "📈", "OK": "✅"}.get(ms["bias"], "❓")
            lines.append(
                f"  _{mtype}_: predicha `{ms['predicted']}%` → real `{ms['hit_rate']}%` "
                f"(n={ms['n']}) {be}"
            )
        if any(mtype != "overall" and ms["n"] >= 3 for mtype, ms in cal_stats.items()):
            lines.append("")
    else:
        lines.append("🔬 _Calibración disponible cuando haya ≥ 5 patas con resultado._")
        lines.append("")

    lines.append("💡 _Usa `/resultado <id> <WLWWL>` para registrar resultados._")
    return "\n".join(lines)
