"""
Parlay History — SQLite-backed persistent storage with adaptive calibration.

Every parlay generated by ``/parlay`` is saved here.  When the user reports
results with ``/resultado``, each leg is marked W(on) / L(ost) / X(void).
That accumulated data feeds a calibration engine that automatically corrects
future probability estimates, making the parlay builder smarter over time.

Storage
-------
``data/parlay_history.db`` — SQLite database (no external dependencies).

Schema::

    parlays(id TEXT PK, created_at TEXT, tier TEXT,
            combined_prob REAL, parlay_result TEXT)

    parlay_legs(id INT PK AUTOINCREMENT, parlay_id TEXT FK,
                leg_order INT, match_name TEXT, pick TEXT,
                market_type TEXT, sport TEXT, league TEXT,
                sport_emoji TEXT, predicted_prob REAL, result TEXT)

If a legacy ``data/parlay_history.json`` file exists it is migrated into the
database on the first access and then renamed to ``.bak``.

Calibration logic
-----------------
For every group (market_type, and optionally sport/league) with ≥
``_MIN_SAMPLES`` resolved legs:

  EWMA-weighted calibration factor:

    w_i = DECAY ^ (N - 1 - i)    (i=0 oldest … i=N-1 most recent)
    predicted_bar = sum(w_i * pred_i) / sum(w_i)
    hit_rate_bar  = sum(w_i * outcome_i) / sum(w_i) * 100

    calibration_factor = hit_rate_bar / predicted_bar

  - Factor < 1 → model is *over*-confident → future probs are scaled down
  - Factor > 1 → model is *under*-confident → future probs are scaled up
  - Clamped to [``_CAL_MIN``, ``_CAL_MAX``] to avoid extreme swings

  Setting ``EWMA_DECAY = 1.0`` degrades gracefully to a simple mean.
"""

from __future__ import annotations

import json
import logging
import math
import os
import re as _re
import sqlite3
import threading
from contextlib import contextmanager
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger(__name__)

# ── Paths ──────────────────────────────────────────────────────────────────────
_BASE_DIR    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # sports_engine/
_DATA_DIR    = os.path.join(_BASE_DIR, "data")
_DB_FILE     = os.path.join(_DATA_DIR, "parlay_history.db")
_LEGACY_JSON = os.path.join(_DATA_DIR, "parlay_history.json")

# ── Concurrency ────────────────────────────────────────────────────────────────
# SQLite handles internal locking; this module-level lock serialises the
# rarely-needed migration and heavy write operations from the bot's event loop.
_LOCK = threading.Lock()

# ── Calibration parameters ─────────────────────────────────────────────────────
# Minimum resolved legs in a group before its calibration factor is trusted.
_MIN_SAMPLES = 5
# Rolling window — only the most recent N resolved legs feed calibration.
# A finite window lets the model adapt to recent form rather than being
# anchored by old data that no longer reflects the current market.
# Override via PARLAY_CAL_WINDOW env var (e.g. "100" for a high-volume bot).
_CALIBRATION_WINDOW: int = int(os.environ.get("PARLAY_CAL_WINDOW", "200"))
# Calibration factor is clamped to this range to prevent extreme corrections
# from small or noisy samples.
_CAL_MIN, _CAL_MAX = 0.60, 1.40
# EWMA decay factor: 0 < EWMA_DECAY ≤ 1.0.
# Values < 1 give more weight to recent resolved legs.
# 1.0 = simple mean (no decay).  0.95 = mild recency bias.
# Override via PARLAY_EWMA_DECAY env var (e.g. "0.90" for faster adaptation).
EWMA_DECAY: float = float(os.environ.get("PARLAY_EWMA_DECAY", "0.95"))

# Compiled regex for validating / matching parlay IDs (e.g. "P240315-2").
# Exported so callers (bot.py) can reuse it without duplicating the pattern.
PARLAY_ID_RE = _re.compile(r'^P\d{6}-\d+$', _re.IGNORECASE)

# ── Schema ─────────────────────────────────────────────────────────────────────
_DDL = """
PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS parlays (
    id            TEXT PRIMARY KEY,
    created_at    TEXT NOT NULL,
    tier          TEXT NOT NULL,
    combined_prob REAL,
    parlay_result TEXT
);

CREATE TABLE IF NOT EXISTS parlay_legs (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    parlay_id      TEXT    NOT NULL REFERENCES parlays(id) ON DELETE CASCADE,
    leg_order      INTEGER NOT NULL,
    match_name     TEXT    NOT NULL DEFAULT '',
    pick           TEXT    NOT NULL DEFAULT '',
    market_type    TEXT    NOT NULL DEFAULT '',
    sport          TEXT    NOT NULL DEFAULT '',
    league         TEXT    NOT NULL DEFAULT '',
    sport_emoji    TEXT    NOT NULL DEFAULT '',
    predicted_prob REAL,
    result         TEXT
);

CREATE INDEX IF NOT EXISTS idx_legs_parlay ON parlay_legs(parlay_id);
CREATE INDEX IF NOT EXISTS idx_legs_result ON parlay_legs(result);
CREATE INDEX IF NOT EXISTS idx_legs_market ON parlay_legs(market_type);
CREATE INDEX IF NOT EXISTS idx_legs_sport  ON parlay_legs(sport);
CREATE INDEX IF NOT EXISTS idx_legs_league ON parlay_legs(league);
"""


# ── Database helpers ───────────────────────────────────────────────────────────

def _ensure_db() -> None:
    """Create the database and tables if they do not yet exist."""
    os.makedirs(_DATA_DIR, exist_ok=True)
    with sqlite3.connect(_DB_FILE) as conn:
        conn.executescript(_DDL)


@contextmanager
def _db():
    """
    Context manager yielding a ``sqlite3.Connection`` with row-factory set.

    Automatically commits on clean exit, rolls back on exception, and ensures
    the schema exists before yielding.
    """
    _ensure_db()
    conn = sqlite3.connect(_DB_FILE, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


# ── Legacy JSON migration ──────────────────────────────────────────────────────

def _migrate_json_if_needed() -> None:
    """
    One-time migration of ``parlay_history.json`` → SQLite.

    After a successful migration the JSON file is renamed to ``.bak`` so it
    is preserved for reference but no longer loaded.
    """
    if not os.path.exists(_LEGACY_JSON):
        return
    # Already migrated?
    bak = _LEGACY_JSON + ".bak"
    if os.path.exists(bak):
        return

    try:
        with open(_LEGACY_JSON, "r", encoding="utf-8") as fh:
            records = json.load(fh)
        if not isinstance(records, list):
            records = []
    except (json.JSONDecodeError, OSError) as exc:
        logger.warning("parlay_history: could not read legacy JSON for migration: %s", exc)
        return

    migrated = 0
    with _db() as conn:
        for rec in records:
            pid = rec.get("id", "")
            if not pid:
                continue
            # Skip if already in DB (idempotent)
            existing = conn.execute(
                "SELECT 1 FROM parlays WHERE id = ?", (pid,)
            ).fetchone()
            if existing:
                continue
            conn.execute(
                "INSERT INTO parlays(id, created_at, tier, combined_prob, parlay_result) "
                "VALUES (?,?,?,?,?)",
                (
                    pid,
                    rec.get("created_at", ""),
                    rec.get("tier", ""),
                    rec.get("combined_prob"),
                    rec.get("parlay_result"),
                ),
            )
            for order, leg in enumerate(rec.get("legs", [])):
                conn.execute(
                    "INSERT INTO parlay_legs"
                    "(parlay_id, leg_order, match_name, pick, market_type, "
                    " sport, league, sport_emoji, predicted_prob, result) "
                    "VALUES (?,?,?,?,?,?,?,?,?,?)",
                    (
                        pid, order,
                        leg.get("match", ""),
                        leg.get("pick", ""),
                        leg.get("market_type", ""),
                        leg.get("sport", ""),
                        leg.get("league", ""),
                        leg.get("sport_emoji", ""),
                        leg.get("predicted_prob"),
                        leg.get("result"),
                    ),
                )
            migrated += 1

    if migrated:
        logger.info("parlay_history: migrated %d records from JSON → SQLite", migrated)

    try:
        os.rename(_LEGACY_JSON, bak)
    except OSError as exc:
        logger.warning("parlay_history: could not rename legacy JSON: %s", exc)


# ── ID generation ──────────────────────────────────────────────────────────────

def _next_id(conn: sqlite3.Connection) -> str:
    """Return the next sequential parlay ID for today, e.g. ``P260315-3``."""
    today  = datetime.now(timezone.utc).strftime("%y%m%d")
    prefix = f"P{today}-"
    row    = conn.execute(
        "SELECT COUNT(*) FROM parlays WHERE id LIKE ?", (prefix + "%",)
    ).fetchone()
    n = row[0] if row else 0
    return f"{prefix}{n + 1}"


# ── Public API — write ─────────────────────────────────────────────────────────

def save_parlay(legs: list, tier: str, combined_prob: Optional[float]) -> str:
    """
    Persist a generated parlay and return its unique ID.

    Parameters
    ----------
    legs         : list of leg dicts from ``generate_parlay_legs``.
                   Expected keys: match, pick, market_type, sport_emoji,
                   prob (or predicted_prob), league, sport (all optional).
    tier         : "safe" | "balanced" | "risky"
    combined_prob: combined probability (%) for this tier's legs

    Returns
    -------
    Unique parlay ID string (e.g. ``"P260315-1"``).
    """
    _migrate_json_if_needed()
    with _LOCK:
        with _db() as conn:
            pid = _next_id(conn)
            now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            conn.execute(
                "INSERT INTO parlays(id, created_at, tier, combined_prob, parlay_result) "
                "VALUES (?,?,?,?,?)",
                (pid, now, tier, combined_prob, None),
            )
            for order, leg in enumerate(legs):
                prob = leg.get("prob") if leg.get("prob") is not None else leg.get("predicted_prob")
                conn.execute(
                    "INSERT INTO parlay_legs"
                    "(parlay_id, leg_order, match_name, pick, market_type, "
                    " sport, league, sport_emoji, predicted_prob, result) "
                    "VALUES (?,?,?,?,?,?,?,?,?,?)",
                    (
                        pid, order,
                        leg.get("match", ""),
                        leg.get("pick", ""),
                        leg.get("market_type", ""),
                        leg.get("sport", ""),
                        leg.get("league", ""),
                        leg.get("sport_emoji", ""),
                        prob,
                        None,
                    ),
                )
        logger.info("parlay_history: saved %s (%d legs, tier=%s)", pid, len(legs), tier)
    return pid


def record_results(parlay_id: str, results: list) -> dict:
    """
    Record win/loss/void results for the legs of a previously saved parlay.

    Parameters
    ----------
    parlay_id : parlay ID string (e.g. ``"P240315-1"``) — case-insensitive.
    results   : list of ``"W"``, ``"L"``, or ``"X"`` (void/cancelled), one
                element per leg.  If shorter than the leg count, remaining
                legs are left as ``None``.

    Returns
    -------
    dict:
      ``found``   – bool
      ``id``      – parlay_id
      ``legs``    – updated legs list (only when found)
      ``overall`` – ``"W"`` / ``"L"`` / ``"X"`` / ``None``
    """
    _migrate_json_if_needed()
    pid_upper = parlay_id.strip().upper()

    with _LOCK:
        with _db() as conn:
            parlay_row = conn.execute(
                "SELECT id FROM parlays WHERE UPPER(id) = ?", (pid_upper,)
            ).fetchone()
            if not parlay_row:
                return {"found": False, "id": parlay_id}

            real_pid = parlay_row["id"]

            # Apply results to each leg by order
            for i, res in enumerate(results):
                conn.execute(
                    "UPDATE parlay_legs SET result = ? "
                    "WHERE parlay_id = ? AND leg_order = ?",
                    (res.strip().upper(), real_pid, i),
                )

            # Re-read all leg results
            leg_rows = conn.execute(
                "SELECT leg_order, match_name, pick, result "
                "FROM parlay_legs WHERE parlay_id = ? ORDER BY leg_order",
                (real_pid,),
            ).fetchall()

            all_results       = [r["result"] for r in leg_rows]
            reported_non_null = [r for r in all_results if r is not None]

            if any(r == "L" for r in reported_non_null):
                overall = "L"
            elif (
                len(reported_non_null) == len(leg_rows)
                and all(r in ("W", "X") for r in reported_non_null)
            ):
                overall = "W"
            else:
                overall = None

            conn.execute(
                "UPDATE parlays SET parlay_result = ? WHERE id = ?",
                (overall, real_pid),
            )

            logger.info(
                "parlay_history: recorded results for %s → %s", real_pid, overall
            )
            legs = [
                {
                    "match": r["match_name"],
                    "pick":  r["pick"],
                    "result": r["result"],
                }
                for r in leg_rows
            ]
            return {
                "found":   True,
                "id":      real_pid,
                "legs":    legs,
                "overall": overall,
            }


def get_last_parlay_id() -> Optional[str]:
    """Return the ID of the most recently generated parlay, or None."""
    _migrate_json_if_needed()
    with _db() as conn:
        row = conn.execute(
            "SELECT id FROM parlays ORDER BY created_at DESC, ROWID DESC LIMIT 1"
        ).fetchone()
    return row["id"] if row else None


# ── Public API — read ──────────────────────────────────────────────────────────

def get_history(limit: int = 20) -> list:
    """Return the ``limit`` most recent parlay records, newest first."""
    _migrate_json_if_needed()
    with _db() as conn:
        parlay_rows = conn.execute(
            "SELECT id, created_at, tier, combined_prob, parlay_result "
            "FROM parlays ORDER BY created_at DESC, ROWID DESC LIMIT ?",
            (limit,),
        ).fetchall()

        result = []
        for p in parlay_rows:
            leg_rows = conn.execute(
                "SELECT match_name, pick, market_type, sport, league, "
                "sport_emoji, predicted_prob, result "
                "FROM parlay_legs WHERE parlay_id = ? ORDER BY leg_order",
                (p["id"],),
            ).fetchall()
            result.append(
                {
                    "id":            p["id"],
                    "created_at":    p["created_at"],
                    "tier":          p["tier"],
                    "combined_prob": p["combined_prob"],
                    "parlay_result": p["parlay_result"],
                    "legs": [
                        {
                            "match":          r["match_name"],
                            "pick":           r["pick"],
                            "market_type":    r["market_type"],
                            "sport":          r["sport"],
                            "league":         r["league"],
                            "sport_emoji":    r["sport_emoji"],
                            "predicted_prob": r["predicted_prob"],
                            "result":         r["result"],
                        }
                        for r in leg_rows
                    ],
                }
            )
    return result


def get_calibration_stats() -> dict:
    """
    Compute EWMA-weighted calibration statistics from resolved legs.

    Groups legs by *market_type* (plus an ``"overall"`` aggregate) using the
    most recent ``_CALIBRATION_WINDOW`` resolved (W or L) legs.

    Returns
    -------
    dict mapping group_key → {
        ``n``          : int   — resolved leg count in window
        ``predicted``  : float — EWMA-weighted predicted probability (%)
        ``hit_rate``   : float — EWMA-weighted actual hit rate (%)
        ``calibration``: float — hit_rate / predicted  (1.0 = perfect)
        ``bias``       : str   — "OVERCONFIDENT" | "UNDERCONFIDENT" | "OK"
    }
    """
    _migrate_json_if_needed()
    # Use a subquery to LIMIT before ordering so the DB only scans the window.
    _sql = (
        "SELECT market_type, predicted_prob, result "
        "FROM (SELECT market_type, predicted_prob, result, id "
        "      FROM parlay_legs "
        "      WHERE result IN ('W','L') AND predicted_prob IS NOT NULL "
        "      ORDER BY id DESC LIMIT ?) "
        "ORDER BY id ASC"
    )
    with _db() as conn:
        rows = conn.execute(_sql, (_CALIBRATION_WINDOW,)).fetchall()

    if not rows:
        return {}

    # Build per-market groups: list of (predicted_prob, outcome) tuples
    groups: dict = {}
    for row in rows:
        key = row["market_type"] or "unknown"
        groups.setdefault(key, [])
        groups[key].append((float(row["predicted_prob"]), 1 if row["result"] == "W" else 0))

    stats: dict = {}
    for mtype, data in groups.items():
        stats[mtype] = _ewma_stats(data)

    # Overall across all market types
    all_data = [(float(r["predicted_prob"]), 1 if r["result"] == "W" else 0) for r in rows]
    stats["overall"] = _ewma_stats(all_data)

    return stats


def get_sport_stats() -> dict:
    """
    Per-sport EWMA calibration stats (same structure as ``get_calibration_stats``).
    """
    _migrate_json_if_needed()
    _sql = (
        "SELECT sport, predicted_prob, result "
        "FROM (SELECT sport, predicted_prob, result, id "
        "      FROM parlay_legs "
        "      WHERE result IN ('W','L') AND predicted_prob IS NOT NULL "
        "      ORDER BY id DESC LIMIT ?) "
        "ORDER BY id ASC"
    )
    with _db() as conn:
        rows = conn.execute(_sql, (_CALIBRATION_WINDOW,)).fetchall()

    groups: dict = {}
    for row in rows:
        key = row["sport"] or "unknown"
        groups.setdefault(key, [])
        groups[key].append((float(row["predicted_prob"]), 1 if row["result"] == "W" else 0))

    return {k: _ewma_stats(v) for k, v in groups.items()}


def get_league_stats() -> dict:
    """
    Per-league EWMA calibration stats (same structure as ``get_calibration_stats``).
    """
    _migrate_json_if_needed()
    _sql = (
        "SELECT league, predicted_prob, result "
        "FROM (SELECT league, predicted_prob, result, id "
        "      FROM parlay_legs "
        "      WHERE result IN ('W','L') AND predicted_prob IS NOT NULL "
        "      ORDER BY id DESC LIMIT ?) "
        "ORDER BY id ASC"
    )
    with _db() as conn:
        rows = conn.execute(_sql, (_CALIBRATION_WINDOW,)).fetchall()

    groups: dict = {}
    for row in rows:
        key = row["league"] or "unknown"
        groups.setdefault(key, [])
        groups[key].append((float(row["predicted_prob"]), 1 if row["result"] == "W" else 0))

    return {k: _ewma_stats(v) for k, v in groups.items()}


def calibrate_prob(prob: float, market_type: str) -> float:
    """
    Return a calibration-adjusted probability for a given market type.

    Falls back to the overall calibration factor when the per-market group
    has fewer than ``_MIN_SAMPLES`` resolved legs.  Returns ``prob`` unchanged
    when no calibration data is available yet.

    The correction factor is clamped to ``[_CAL_MIN, _CAL_MAX]`` to prevent
    extreme swings from small or noisy samples.
    """
    stats  = get_calibration_stats()
    factor = _get_factor(stats.get(market_type))
    if factor is None:
        factor = _get_factor(stats.get("overall"))
    if factor is None:
        return prob  # no data yet — return unchanged

    adjusted = prob * factor
    return round(max(1.0, min(99.0, adjusted)), 1)


# ── EWMA helpers ───────────────────────────────────────────────────────────────

def _ewma_stats(data: list) -> dict:
    """
    Compute EWMA-weighted calibration stats from a list of (predicted, outcome) tuples.

    The most recent entry (last in list) gets weight 1.0; earlier entries get
    ``EWMA_DECAY^k`` where k is how many steps back they are.
    """
    n = len(data)
    if n == 0:
        return {"n": 0, "predicted": 0.0, "hit_rate": 0.0,
                "calibration": 1.0, "bias": "OK"}

    weights = [EWMA_DECAY ** (n - 1 - i) for i in range(n)]
    w_sum   = sum(weights)

    w_pred = sum(w * d[0] for w, d in zip(weights, data)) / w_sum
    w_hit  = sum(w * d[1] for w, d in zip(weights, data)) / w_sum * 100.0

    cal = w_hit / w_pred if w_pred > 0 else 1.0
    return {
        "n":           n,
        "predicted":   round(w_pred, 1),
        "hit_rate":    round(w_hit, 1),
        "calibration": round(cal, 3),
        "bias":        _bias_label(cal),
    }


def _bias_label(cal: float) -> str:
    if cal < 0.85:
        return "OVERCONFIDENT"
    if cal > 1.15:
        return "UNDERCONFIDENT"
    return "OK"


def _get_factor(group_stats: Optional[dict]) -> Optional[float]:
    """Return clamped calibration factor from a stats dict, or None."""
    if not group_stats or group_stats["n"] < _MIN_SAMPLES:
        return None
    raw = group_stats["calibration"]
    return max(_CAL_MIN, min(_CAL_MAX, raw))


# ── Deep analytics ─────────────────────────────────────────────────────────────

def get_trend(n_last: int = 20) -> list:
    """
    Return the win/loss trend for the last ``n_last`` *resolved* parlays.

    Returns
    -------
    list of dicts: [{id, created_at, result, combined_prob}, …] oldest-first.
    """
    _migrate_json_if_needed()
    with _db() as conn:
        rows = conn.execute(
            "SELECT id, created_at, parlay_result, combined_prob "
            "FROM parlays WHERE parlay_result IN ('W','L') "
            "ORDER BY created_at DESC, ROWID DESC LIMIT ?",
            (n_last,),
        ).fetchall()
    return list(reversed([dict(r) for r in rows]))


# ── Telegram formatters ────────────────────────────────────────────────────────

_NUMBERS      = ["1️⃣", "2️⃣", "3️⃣", "4️⃣", "5️⃣"]
_RESULT_EMOJI = {"W": "✅", "L": "❌", "X": "⬜"}
_TIER_EMOJI   = {"safe": "🟢", "balanced": "🟡", "risky": "🔴"}


def format_result_confirmation(record: dict) -> str:
    """Format a result-recording confirmation message for Telegram."""
    pid    = record.get("id", "?")
    legs   = record.get("legs", [])
    ov     = record.get("overall")
    ov_str = {"W": "✅ GANADO", "L": "❌ PERDIDO"}.get(ov, "⏳ Parcialmente registrado")

    lines = [
        f"📋 *Resultados registrados — {pid}*",
        "━━━━━━━━━━━━━━━━━━━━",
    ]
    for i, leg in enumerate(legs):
        num  = _NUMBERS[i] if i < len(_NUMBERS) else f"{i+1}."
        res  = leg.get("result")
        icon = _RESULT_EMOJI.get(res, "⏳") if res else "⏳"
        lines.append(f"  {num} {icon} *{leg['match']}* → _{leg['pick']}_")

    lines += [
        "",
        f"📊 Resultado del parlay: *{ov_str}*",
        "",
        "_Gracias — los datos se usarán para mejorar futuras predicciones._",
    ]
    return "\n".join(lines)


def format_history_summary(records: list, cal_stats: dict) -> str:
    """Format the /historial summary message for Telegram."""
    lines = [
        "╔══════════════════════════════════╗",
        "  📊 HISTORIAL DE PARLAYS",
        "╚══════════════════════════════════╝",
        "",
    ]

    # ── Recent parlays ──────────────────────────────────────────────────
    if records:
        lines.append("🗓️ *ÚLTIMOS PARLAYS*")
        lines.append("━━━━━━━━━━━━━━━━━━━━")
        for rec in records[:10]:
            pid     = rec.get("id", "?")
            tier    = rec.get("tier", "?")
            tier_e  = _TIER_EMOJI.get(tier, "⚪")
            cp      = rec.get("combined_prob")
            cp_str  = f"`{cp}%`" if cp is not None else "`?`"
            ov      = rec.get("parlay_result")
            ov_icon = _RESULT_EMOJI.get(ov, "⏳")
            n_legs  = len(rec.get("legs", []))
            date_s  = rec.get("created_at", "")[:10]
            lines.append(
                f"  {ov_icon} `{pid}` {tier_e} {tier.upper()} "
                f"({n_legs} patas, {cp_str}) — {date_s}"
            )
        lines.append("")
    else:
        lines.append("_Aún no hay parlays registrados._")
        lines.append("")

    # ── Win rates ────────────────────────────────────────────────────────
    total_resolved = [r for r in records if r.get("parlay_result") in ("W", "L")]
    if total_resolved:
        wins  = sum(1 for r in total_resolved if r["parlay_result"] == "W")
        total = len(total_resolved)
        lines += [
            "🏆 *RENDIMIENTO*",
            "━━━━━━━━━━━━━━━━━━━━",
            f"  Parlays ganados: *{wins}/{total}* ({round(wins/total*100)}%)",
            "",
        ]

    # ── Calibration stats ────────────────────────────────────────────────
    ov_cal = cal_stats.get("overall")
    if ov_cal and ov_cal["n"] >= 3:
        be = {"OVERCONFIDENT": "📉", "UNDERCONFIDENT": "📈", "OK": "✅"}.get(
            ov_cal["bias"], "❓"
        )
        lines += [
            "🔬 *CALIBRACIÓN DEL MODELO*",
            "━━━━━━━━━━━━━━━━━━━━",
            f"  Patas analizadas: `{ov_cal['n']}`",
            f"  Prob. predicha promedio: `{ov_cal['predicted']}%`",
            f"  Tasa de acierto real: `{ov_cal['hit_rate']}%`",
            f"  Factor de calibración: `{ov_cal['calibration']}`  {be} {ov_cal['bias']}",
            "",
        ]
        for mtype, ms in cal_stats.items():
            if mtype == "overall" or ms["n"] < 3:
                continue
            be2 = {"OVERCONFIDENT": "📉", "UNDERCONFIDENT": "📈", "OK": "✅"}.get(
                ms["bias"], "❓"
            )
            lines.append(
                f"  _{mtype}_: predicha `{ms['predicted']}%` → real `{ms['hit_rate']}%` "
                f"(n={ms['n']}) {be2}"
            )
        if any(k != "overall" and v["n"] >= 3 for k, v in cal_stats.items()):
            lines.append("")
    else:
        lines.append("🔬 _Calibración disponible cuando haya ≥ 5 patas con resultado._")
        lines.append("")

    lines.append("💡 _Usa `/resultado <id> <WLWWL>` para registrar resultados._")
    return "\n".join(lines)


def format_estadisticas(cal_stats: dict, sport_stats: dict,
                        league_stats: dict, trend: list) -> str:
    """Format the /estadisticas deep-analytics message for Telegram."""
    lines = [
        "╔══════════════════════════════════╗",
        "  🧠 ESTADÍSTICAS DEL MOTOR",
        "╚══════════════════════════════════╝",
        "",
    ]

    ov = cal_stats.get("overall")
    if ov and ov["n"] >= 1:
        be = {"OVERCONFIDENT": "📉", "UNDERCONFIDENT": "📈", "OK": "✅"}.get(ov["bias"], "❓")
        lines += [
            "📊 *RESUMEN GLOBAL*",
            "━━━━━━━━━━━━━━━━━━━━",
            f"  Patas resueltas: `{ov['n']}`",
            f"  Predicción promedio: `{ov['predicted']}%`",
            f"  Acierto real (EWMA): `{ov['hit_rate']}%`",
            f"  Factor calibración: `{ov['calibration']}`  {be}",
            "",
        ]
    else:
        lines += [
            "_Sin datos suficientes aún — registra resultados con `/resultado`._",
            "",
        ]

    # ── Trend sparkline ──────────────────────────────────────────────────
    if trend:
        wins_seq  = ["✅" if r.get("parlay_result") == "W" else "❌" for r in trend]
        sparkline = "".join(wins_seq[-10:])
        n_w = wins_seq.count("✅")
        n_t = len(wins_seq)
        lines += [
            "📈 *TENDENCIA RECIENTE*",
            "━━━━━━━━━━━━━━━━━━━━",
            f"  {sparkline}",
            f"  {n_w}/{n_t} ganados ({round(n_w/n_t*100) if n_t else 0}%)",
            "",
        ]

    # ── Per-sport breakdown ──────────────────────────────────────────────
    if sport_stats:
        lines += [
            "⚽🏀 *POR DEPORTE*",
            "━━━━━━━━━━━━━━━━━━━━",
        ]
        for sport, s in sorted(sport_stats.items(), key=lambda x: -x[1]["n"]):
            if s["n"] < 2:
                continue
            be = {"OVERCONFIDENT": "📉", "UNDERCONFIDENT": "📈", "OK": "✅"}.get(s["bias"], "❓")
            lines.append(
                f"  _{sport}_: `{s['hit_rate']}%` acierto "
                f"(n={s['n']}) {be}"
            )
        lines.append("")

    # ── Per-league breakdown ─────────────────────────────────────────────
    good_leagues = {k: v for k, v in league_stats.items() if v["n"] >= 3}
    if good_leagues:
        lines += [
            "🏆 *POR LIGA*",
            "━━━━━━━━━━━━━━━━━━━━",
        ]
        for league, s in sorted(good_leagues.items(), key=lambda x: -x[1]["hit_rate"]):
            be = {"OVERCONFIDENT": "📉", "UNDERCONFIDENT": "📈", "OK": "✅"}.get(s["bias"], "❓")
            lines.append(
                f"  _{league}_: `{s['hit_rate']}%` acierto "
                f"(n={s['n']}) {be}"
            )
        lines.append("")

    # ── Per-market type ──────────────────────────────────────────────────
    good_markets = {k: v for k, v in cal_stats.items() if k != "overall" and v["n"] >= 3}
    if good_markets:
        lines += [
            "📋 *POR TIPO DE MERCADO*",
            "━━━━━━━━━━━━━━━━━━━━",
        ]
        for mtype, s in sorted(good_markets.items(), key=lambda x: -x[1]["hit_rate"]):
            be = {"OVERCONFIDENT": "📉", "UNDERCONFIDENT": "📈", "OK": "✅"}.get(s["bias"], "❓")
            lines.append(
                f"  _{mtype}_: predicha `{s['predicted']}%` → real `{s['hit_rate']}%` "
                f"(n={s['n']}) {be}"
            )
        lines.append("")

    lines += [
        "💡 _Las probabilidades de futuros parlays se ajustan automáticamente._",
        "📝 _Registra resultados con `/resultado <id> WLW`_",
    ]
    return "\n".join(lines)
